project:
  type: book
  output-dir: docs

book:
  title: "Group_1 Quarto Book Part2"
  author: "Group 1"
  date: "9/1/2024"
  chapters:
    - indexP2.qmd
    - introP2.qmd
    - Saul-FinalProj.qmd
    - Bridget-FinalProj.qmd
    - Daniela-FinalProj.qmd
    - Victorious-FinalProj.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: BarlowCondensed.css
pdf:
documentclass: scrreprt




