project:
  type: book
  output-dir: docs

book:
  title: "Group_1 Quarto Book"
  author: "Group 1"
  date: "9/1/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - Saul.qmd
    - Bridget.qmd
    - Tut2_Python_Jaen_092024.ipynb
    - Tut3_Python_Jaen.ipynb
    - Tut4_Python_Plotnine_Jaen.ipynb
    - Daniela.qmd
    - Tut2_Python_Daniela_092324.ipynb
    - Victorious.qmd
    - Tut2_Python_vfashina_092024.ipynb
    - Tut4_Python_vfashina_092724.ipynb
    - Tut5_Python_Vfashina_093024.ipynb
    - Part2_Intro.qmd
    - Bridget_Deliverable 1.qmd
    - Irma-Miami-Dade-Stations.qmd
    - Daniela2.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
pdf:
documentclass: scrreprt




