---
title: "Midterm_Jaen_Dashboard"
format: html
---

## Dataset

This dataset is about Airquality focused on air pollutants, specifically ozone. Ozone is a harmful gas formed when pollutants from vehicles, industries, and other sources react with sunlight. We will look into the levels in Florida, Miami,Fort Lauderdale, and West Palm Beach. Specifically in the Miami-Dade county. The source is the EDA website and the year we are focusing in is 2023. There are 21 variables in this dataset and 710 observations. The variables are Date, Source, Site ID, POC, Daily Max 8-hour Ozone Concentration, Units, Daily AQI Value, Local Site Name, Daily Obs Count, Percent Complete, AQS Parameter code, AQS Parameter Description, Method Code, CBSA Code, CBSA Name, State FIPS Code, State, County FIPS Code, County, Site Latitude, and Site Longitude.

## Tableau

I went to Tableau's public access website and created an account to access Tableau. On the top left, I went to create and select web authoring. There, I uploaded my file (dataset).

Tableau recognized that my data set had locations, so I could play around with maps and geographic locations, which was really fun.

It was a little hard to continue using the variables that I had previously used in the past weeks, so I had to opt for others, which still told me valuable information about the dataset. The option "show me more" was also very useful in making the graphs.

## Dashboard

To create a dashboard in Tableau, I followed these steps:

1.  Build and customize the graphs: I started by creating a graph. Once I was satisfied with the first one, I duplicated it, modified the variables, and adjusted the graph type to suit my needs. I dragged the variables into elements like size, color, or shape for further customization. When unsure about the best graph type to use, Tableau provides suggestions through the "Show Me" feature, which offers additional visualization options. I used filters and parameters in cases where the graphs were too long. 

2.  Use columns and rows: When setting up the graph, I tried placing string (categorical) values in the columns and numerical values in the rows. This layout often helps to ensure the visualization tells a coherent story. I then check if the data makes sense, both visually and contextually.

3.  Repeat for multiple graphs: After completing one graph, I repeated the process to create at least four different visualizations. This provided a diverse set of insights for the dashboard.

4.  Create the dashboard: Once all my graphs were ready, I clicked the dashboard button located next to the sheet number. In this view, you can adjust the height and width of your dashboard to your desired dimensions.

5.  Drag and Organize Sheets: I dragged the sheets with graphs into the dashboard workspace. Then, I arrange and organize them to create a clean, logical layout.

6.  Publish and Share: I published the dashboard when I was happy with the final design. After publishing, I clicked the "Share" button and copied the provided link to distribute my work.

The types of charts I used are map, scatter plot, bar chart, and area chart.

## Link

https://public.tableau.com/views/MidtermDashboard_17262890293270/Dashboard1?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
